version: '3.7'

services:
  nest:
    container_name: nest
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    restart: always
    ports:
      - "9980:80"
    volumes:
      - .:/usr/src/app:cached
      - ./.env.local:/usr/src/app/.env:cached
      - ./docker/oauth/dev/oauth-public.key:/usr/src/app/storage/oauth-public.key:cached
      - ./docker/oauth/dev/oauth-public.key:/usr/src/app/storage/oauth-public.test.key:cached
      - /usr/src/app/node_modules
    environment:
      APP_ENV: local
      NODE_ENV: local
      HTTPS_METHOD: noredirect # support both http and https
    extra_hosts:
      - api-nest.eggsmartpos.local:127.0.0.1
    networks:
      network-horeca:
        aliases:
          - api-nest.eggsmartpos.local
      network-graylog:
    healthcheck:
      test: curl -f http://api-payment.eggsmartpos.local
      start_period: 30s
      interval: 30s
      timeout: 15s
      retries: 3

networks:
  network-horeca:
    external: true
  network-graylog:
    external: true